name: Build And Deploy Vue

on:
  push:
    branches: [ "main", "feature/landing-page" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./LandingPage
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'Udiknedormin'
          reponame: 'CompassOfWomanhood'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          useyarn: true
