name: Build markdowns

on:
  push:
    paths:
      - 'CompassOfWomanhood/translations/**.md'
      - '!CompassOfWomanhood/translations/*/readme.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Running on the current branch branch.
        run: |
          echo "Running on current: ${{ github.head_ref }}"
      - name: Install merge markdown
        run: npm install -g @knennigtri/merge-markdown
      - name: Merge markdowns
        run: |
          merge-markdown -m ${{ env.translationsPath }}/pl_PL --nolinkcheck
          merge-markdown -m ${{ env.translationsPath }}/en_US --nolinkcheck
        env:
          translationsPath: 'CompassOfWomanhood/translations'

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: publisher@udiknedormin.github.io
          author_name: Github Publisher [bot]
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Publishing merged markdowns for branch ${{ github.head_ref }}
          branch: ${{ github.head_ref }}
          force: true


